//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMNS.ServiceModel.Service.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryEntity
    {
        public CategoryEntity()
        {
            this.ProductEntities = new HashSet<ProductEntity>();
        }
    
        public int CategoryID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<ProductEntity> ProductEntities { get; set; }
    }
}
