//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMNS.ServiceModel.Service.DL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbnailsupplyEntities : DbContext
    {
        public dbnailsupplyEntities()
            : base("name=dbnailsupplyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CategoryEntity> CategoryEntities { get; set; }
        public DbSet<CustomerEntity> CustomerEntities { get; set; }
        public DbSet<EmployeeCategoryEntity> EmployeeCategoryEntities { get; set; }
        public DbSet<EmployeeEntity> EmployeeEntities { get; set; }
        public DbSet<EmployeeLogEntity> EmployeeLogEntities { get; set; }
        public DbSet<InventoryEntity> InventoryEntities { get; set; }
        public DbSet<PaymentEntity> PaymentEntities { get; set; }
        public DbSet<ProductEntity> ProductEntities { get; set; }
        public DbSet<ProductExportDetailEntity> ProductExportDetailEntities { get; set; }
        public DbSet<ProductExportEntity> ProductExportEntities { get; set; }
        public DbSet<ProductImportDetailEntity> ProductImportDetailEntities { get; set; }
        public DbSet<ProductImportEntity> ProductImportEntities { get; set; }
        public DbSet<ProductReturnDetailEntity> ProductReturnDetailEntities { get; set; }
        public DbSet<ProductReturnEntity> ProductReturnEntities { get; set; }
        public DbSet<ProviderEntity> ProviderEntities { get; set; }
    }
}
