//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMNS.ServiceModel.Service.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeCategoryEntity
    {
        public EmployeeCategoryEntity()
        {
            this.EmployeeEntities = new HashSet<EmployeeEntity>();
        }
    
        public int EmployeeCategoryID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<EmployeeEntity> EmployeeEntities { get; set; }
    }
}
