//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMNS.ServiceModel.Service.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeEntity
    {
        public EmployeeEntity()
        {
            this.EmployeeLogEntities = new HashSet<EmployeeLogEntity>();
        }
    
        public int EmployeeID { get; set; }
        public int EmployeeCategoryID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual EmployeeCategoryEntity EmployeeCategoryEntity { get; set; }
        public virtual ICollection<EmployeeLogEntity> EmployeeLogEntities { get; set; }
    }
}
