//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMNS.ServiceModel.Service.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryEntity
    {
        public InventoryEntity()
        {
            this.ProductExportDetailEntities = new HashSet<ProductExportDetailEntity>();
            this.ProductImportDetailEntities = new HashSet<ProductImportDetailEntity>();
        }
    
        public int InventoryID { get; set; }
        public string UPCBarCode { get; set; }
        public Nullable<int> TotalQuantity { get; set; }
        public Nullable<int> ProductStatus { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Location { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual ICollection<ProductExportDetailEntity> ProductExportDetailEntities { get; set; }
        public virtual ICollection<ProductImportDetailEntity> ProductImportDetailEntities { get; set; }
    }
}
