//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMNS.ServiceModel.Service.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentEntity
    {
        public int PaymentID { get; set; }
        public int ProductExportID { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<decimal> TotalDiscountAmount { get; set; }
        public Nullable<decimal> TotalTaxAmount { get; set; }
        public Nullable<decimal> TotalItemAmount { get; set; }
        public Nullable<decimal> TotalPayment { get; set; }
        public string PaymentType { get; set; }
        public string Cashier { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual ProductExportEntity ProductExportEntity { get; set; }
    }
}
