//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMNS.ServiceModel.Service.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductExportEntity
    {
        public ProductExportEntity()
        {
            this.PaymentEntities = new HashSet<PaymentEntity>();
            this.ProductExportDetailEntities = new HashSet<ProductExportDetailEntity>();
            this.ProductReturnEntities = new HashSet<ProductReturnEntity>();
        }
    
        public int ProductExportID { get; set; }
        public string ExportBarcode { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<System.DateTime> ExportDate { get; set; }
        public Nullable<int> TotalQuantity { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> SubTax { get; set; }
        public Nullable<decimal> SubDiscount { get; set; }
        public Nullable<decimal> FinalSalePrice { get; set; }
        public Nullable<decimal> TotalImportPrice { get; set; }
        public Nullable<bool> Status { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual CustomerEntity CustomerEntity { get; set; }
        public virtual ICollection<PaymentEntity> PaymentEntities { get; set; }
        public virtual ICollection<ProductExportDetailEntity> ProductExportDetailEntities { get; set; }
        public virtual ICollection<ProductReturnEntity> ProductReturnEntities { get; set; }
    }
}
