//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMNS.ServiceModel.Service.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductEntity
    {
        public int ProductID { get; set; }
        public int ProviderID { get; set; }
        public int CategoryID { get; set; }
        public string Name { get; set; }
        public string UPCBarCode { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<decimal> ImportPrice { get; set; }
        public string UPCType { get; set; }
        public string Description { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual CategoryEntity CategoryEntity { get; set; }
        public virtual ProviderEntity ProviderEntity { get; set; }
    }
}
