//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMNS.ServiceModel.Service.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductReturnEntity
    {
        public ProductReturnEntity()
        {
            this.ProductReturnDetailEntities = new HashSet<ProductReturnDetailEntity>();
        }
    
        public int ProductReturnID { get; set; }
        public string ProductReturnBarcode { get; set; }
        public int ProductExportID { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<int> TotalItemReturn { get; set; }
        public Nullable<decimal> TotalPriceReturn { get; set; }
        public Nullable<decimal> TotalTaxReturn { get; set; }
        public Nullable<decimal> TotalDiscountReturn { get; set; }
        public Nullable<decimal> FinalPriceReturn { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual ProductExportEntity ProductExportEntity { get; set; }
        public virtual ICollection<ProductReturnDetailEntity> ProductReturnDetailEntities { get; set; }
    }
}
