//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMNS.ServiceModel.Service.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductReturnDetailEntity
    {
        public int ProductReturnDetailEntityID { get; set; }
        public int ProductReturnID { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public string UPCBarCode { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> PriceReturn { get; set; }
        public Nullable<decimal> TaxReturn { get; set; }
        public Nullable<decimal> DiscountReturn { get; set; }
        public Nullable<decimal> FinalPriceReturn { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual ProductReturnEntity ProductReturnEntity { get; set; }
    }
}
