//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMNS.ServiceModel.Service.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductImportDetailEntity
    {
        public int ProductImportDetailID { get; set; }
        public int ProductImportID { get; set; }
        public int InventoryID { get; set; }
        public string UPCBarCode { get; set; }
        public Nullable<int> InQuantity { get; set; }
        public Nullable<int> OutQuantity { get; set; }
        public Nullable<System.DateTime> ImportDate { get; set; }
        public Nullable<decimal> ItemImportPrice { get; set; }
        public Nullable<decimal> TotalImportPrice { get; set; }
        public Nullable<int> ItemImportStatus { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual InventoryEntity InventoryEntity { get; set; }
        public virtual ProductImportEntity ProductImportEntity { get; set; }
    }
}
