//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMNS.ServiceModel.Service.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductExportDetailEntity
    {
        public int ProductExportDetailID { get; set; }
        public int ProductExportID { get; set; }
        public int InventoryID { get; set; }
        public string UPCBarCode { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> ExportDate { get; set; }
        public Nullable<decimal> ItemPrice { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual InventoryEntity InventoryEntity { get; set; }
        public virtual ProductExportEntity ProductExportEntity { get; set; }
    }
}
